#!/usr/bin/env bash
# scripts/update-claude-md.sh
# Regenerates CLAUDE.md from live repo analysis + static guidance.
# Run after adding tools, changing configs, or when CLAUDE.md feels stale.
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$DOTFILES_DIR/CLAUDE.md"
cd "$DOTFILES_DIR"

GENERATED_AT="$(date +%Y-%m-%d)"
BREW_F="$(grep -c '^brew ' homebrew/Brewfile 2>/dev/null || echo 0)"
BREW_C="$(grep -c '^cask ' homebrew/Brewfile 2>/dev/null || echo 0)"

recent_commits() {
  git log --pretty=format:"| \`%h\` | %ad | %s |" --date=short -10
}

hot_files() {
  git log --format="" --name-only | grep -v '^$' | sort | uniq -c | sort -rn | head -10 \
    | awk '{printf "| %-45s | %s changes |\n", $2, $1}'
}

commit_types() {
  git log --pretty=format:"%s" \
    | grep -E '^(feat|fix|chore|docs|refactor|test|style|perf):' \
    | sed 's/:.*//' | sort | uniq -c | sort -rn \
    | awk '{printf "  - **%s**: %d commits\n", $2, $1}'
}

nvim_plugins() {
  ls nvim/nvim/lua/plugins/*.lua 2>/dev/null | while read -r f; do
    printf '  - `%s.lua`\n' "$(basename "$f" .lua)"
  done
}

# ── write file section by section ─────────────────────────────────────────────
{

# HEADER
printf '# CLAUDE.md\n\n'
printf '> Auto-generated by `scripts/update-claude-md.sh` — last updated **%s**.\n' "$GENERATED_AT"
printf '> Run `bash scripts/update-claude-md.sh` to refresh after config changes.\n\n'
printf 'Project-level guidance for Claude Code when working in this dotfiles repository.\n'
printf 'See `~/.claude/CLAUDE.md` (→ `claude/CLAUDE.md`) for global user/style preferences.\n\n'
printf -- '---\n\n'

# QUICK REFERENCE — static block, quoted heredoc keeps backticks literal
cat << 'QUICK_REF'
## Quick Reference

### Core Workflow

```bash
./install.sh                               # full idempotent install
make test-dotfiles                         # run all 6 test suites
bash scripts/update-claude-md.sh          # regenerate this file

stow <pkg> --restow                        # relink a single stow package
stow */ -v2                               # relink all packages

brew bundle --file=homebrew/Brewfile       # install/sync Homebrew tools
tmux source-file ~/.config/tmux/tmux.conf  # reload tmux config live
```

### Claude Code Aliases (`aliases/aliases`)

| Alias | Command | Purpose |
|-------|---------|---------|
| `cc`   | `claude`            | Open Claude Code |
| `ccc`  | `claude --continue` | Resume last session |
| `ccr`  | `claude --resume`   | Pick a past session |
| `ccp`  | `claude --print`    | Non-interactive output |
| `gcai` | `git diff --cached \| copilot` | AI conventional commit from staged diff |

### Git Aliases (`git/git/config`)

| Alias    | Expands to |
|----------|-----------|
| `g st`   | `git status -sb` |
| `g lg`   | `git log --oneline --graph --decorate --all` |
| `g wip`  | stage all + commit "WIP" |
| `g amend`| `git commit --amend --no-edit` |
| `g last` | `git log -1 HEAD --stat` |

### Shell Aliases (`aliases/aliases`)

```bash
ls / la / lt    # lsd  /  lsd -la  /  lsd --tree
cat             # bat -p  (syntax-highlighted, no pager)
rm              # trash -v  (safe delete, recoverable from Trash)
g               # git
gs / gl / gd    # git status -sb  /  log --oneline  /  diff
```

---

## Architecture

### Directory Structure

QUICK_REF

# Directory tree — dynamic brew counts
printf 'dotfiles/\n'
printf '├── alacritty/          → ~/.config/alacritty/    terminal emulator config\n'
printf '├── aliases/            → ~/.config/aliases        shell aliases (sourced by .zshrc)\n'
printf '├── claude/             → ~/.claude/               Claude Code config + local marketplace\n'
printf '├── copilot/            → ~/.copilot/              Copilot CLI custom instructions\n'
printf '├── git/                → ~/.config/git/           XDG-compliant git config + global ignore\n'
printf '├── homebrew/           Brewfile (%s formulas, %s casks) + prerequisite snapshots\n' "$BREW_F" "$BREW_C"
printf '├── nvim/               → ~/.config/nvim/          LazyVim-based Neovim\n'
printf '├── osx/                macOS automations (applied manually, not stowed)\n'
printf '├── scripts/            repo maintenance scripts\n'
printf '├── starship/           → ~/.config/starship.toml  prompt config\n'
printf '├── tests/              dotfiles test suite (make test-dotfiles)\n'
printf '├── tmux/               → ~/.config/tmux/          TPM-managed tmux config\n'
printf '└── zsh/                → ~/.config/.zshrc         zsh config (sourced via ~/.zshrc)\n'
printf '\n'

cat << 'ARCH_STATIC'
### Stow Layout Rule

Every stow package uses **double-nesting**: `<pkg>/<pkg>/` → `~/.config/<pkg>/`.
Example: `nvim/nvim/init.lua` → `~/.config/nvim/init.lua`

**Packages managed by `install.sh` stow loop:**
`alacritty  aliases  git  homebrew  nvim  starship  tmux  zsh`

Note: `claude`, `copilot`, `osx` are **not** in the stow loop — handled with explicit `ln -sf` calls.

**Special symlinks** (outside `~/.config`):

| Source | Target | Notes |
|--------|--------|-------|
| `zsh/.zshrc` | `~/.zshrc` sources it | macOS reads `~/.zshrc` directly |
| `claude/CLAUDE.md` | `~/.claude/CLAUDE.md` | global Claude Code context |
| `claude/settings.json` | `~/.claude/settings.json` | Claude Code permissions |
| `claude/local-marketplace` | `~/.claude/local-marketplace` | local plugin marketplace |
| `copilot/copilot-instructions.md` | `~/.copilot/` | Copilot CLI custom prompt |
| `.markdownlint.json` | `~/` | markdownlint config |
| TPM | `~/.tmux/plugins/tpm` | cloned by `install.sh` |

---

## Config Packages

### `nvim/` — Neovim (LazyVim)

Entry: `nvim/nvim/init.lua` → bootstraps `config/lazy.lua`

**Plugin files** (`nvim/nvim/lua/plugins/`):
ARCH_STATIC

# Dynamic nvim plugin list
nvim_plugins

cat << 'NVIM_STATIC'

**Config files** (`nvim/nvim/lua/config/`):
- `lazy.lua` — lazy.nvim bootstrap + plugin spec
- `keymaps.lua` — custom keymaps (most keys live in plugin files)
- `options.lua` — vim options (clipboard, line numbers, winbar, cursorcolumn)
- `autocmds.lua` — custom autocommands

**AI keybindings** (`ai.lua`):

| Key | Action |
|-----|--------|
| `<leader>aa` | Toggle Copilot Chat |
| `<leader>ac` | Open Claude Code terminal |
| `<leader>ae` | Explain selection (visual) |
| `<leader>af` | Fix selection (visual) |
| `<leader>ao` | Optimize selection (visual) |
| `<leader>ar` | Review selection (visual) |
| `<leader>at` | Generate tests (visual) |
| `<leader>ad` | Generate docs (visual) |
| `<leader>av` | Toggle Avante |
| `<Tab>` | Accept Copilot inline suggestion |

**DAP keybindings** (`nvimdap.lua`, requires `llvm` → `lldb-dap`):

| Key | Action |
|-----|--------|
| `<space>b` | Toggle breakpoint |
| `<F1>`–`<F5>` | continue / step_into / step_over / step_out / step_back |
| `<F13>` | Restart debug session |
| `<space>?` | Eval var under cursor (dapui) |

### `tmux/` — Tmux

NVIM_STATIC

# tmux prefix line — use printf to avoid backtick issues in heredoc
printf 'Prefix: `` ` `` (backtick). Plugins managed by TPM.\n\n'

cat << 'TMUX_STATIC'
| Binding | Action |
|---------|--------|
| `` ` `` + `\|` | Split horizontal |
| `` ` `` + `-` | Split vertical |
| `` ` `` + `a` | Open Claude Code (50% vertical split) |
| `` ` `` + `p` | Floax floating pane |
| `` ` `` + `o` | Session picker (sessionx + zoxide) |
| `` ` `` + `v` | Enter copy mode |
| `` ` `` + `Ctrl-I` | Install plugins |

Plugins: tpm, sensible, resurrect, continuum, tmux-fzf, fzf-url, floax, catppuccin, sessionx

### `zsh/` — Zsh

Load order: zsh-syntax-highlighting → zsh-vi-mode → fzf → aliases → starship → zsh-autosuggestions

Secrets sourced conditionally (file not in repo):
```bash
[[ -f "$HOME/.config/secrets" ]] && source "$HOME/.config/secrets"
```

### `git/` — Git

XDG-compliant config at `~/.config/git/config`. Pager: `delta` with `gruvbox-dark` and side-by-side diffs.
Pull: `rebase = true`. Merge style: `zdiff3`. Diff algorithm: `histogram`.

### `aliases/` — Shell Aliases

Grouped by domain: unix utilities, git, bat/cat, rust/cargo, config shortcuts,
Bitcoin (regtest/signet daemons + CLI), AWS/RDS tunnels, AI tools (Copilot + Claude).

### `starship/` — Starship Prompt

Shows: cwd (last component), git branch/status, AWS profile + region, language versions, command duration.
Config: `starship/starship.toml` → `~/.config/starship.toml`.

### `alacritty/` — Alacritty

JetBrainsMono Nerd Font 18pt. Opacity 0.9. `option_as_alt = "Both"`. `TERM=xterm-256color`.

### `claude/` — Claude Code Global Config

- `CLAUDE.md` → `~/.claude/CLAUDE.md` — user profile, tech stack, comm preferences (all projects)
- `settings.json` → `~/.claude/settings.json` — bash allow/deny lists, enabled plugins
- `local-marketplace/` → `~/.claude/local-marketplace/` — dotfiles-tools plugin
  - Skill: `/dotfiles-tools:dotfiles-check` — full health check (116 checks)

---

## Conventions

### Commit Style

Conventional Commits enforced. Format: `type: lowercase imperative subject` (no period, ≤72 chars).

Types used in this repo:
TMUX_STATIC

# Dynamic commit type frequency
commit_types

cat << 'CONV_STATIC'

**Examples from history:**
- `feat: add Claude Code CLI integration`
- `fix: remove starship init guard that breaks tmux session restore`
- `chore: dotfiles health check fixes`
- `docs: update README and CLAUDE.md to reflect current state`
- `test: add dotfiles test suite with make test-dotfiles`

### Hot Spots (most-changed files)

These files change most frequently — most likely to need attention after any refactor:

| File | Activity |
|------|----------|
CONV_STATIC

# Dynamic hot files table
hot_files

cat << 'PATTERNS_STATIC'

### Code Patterns

- **Lua plugins**: return a single table; use `opts =` (not `config =`) when possible; declare keybinds in `keys =`
- **Shell scripts**: `set -euo pipefail`; colored output via `pass()`/`fail()`/`warn()` functions
- **Aliases**: grouped by domain with `# comment` headers; no spaces around `=`
- **Stow packages**: double-nested (`pkg/pkg/file`); never put files directly at package root
- **JSON**: ignored globally (`*.json`) with `!claude/**/*.json` exception for Claude configs
- **Secrets**: always guarded with `[[ -f path ]] && source path`; never committed

---

## Recent Changes

| Hash | Date | Message |
|------|------|---------|
PATTERNS_STATIC

# Dynamic recent commits
recent_commits

cat << 'FOOTER_STATIC'

---

## Testing

```bash
make test-dotfiles    # run all suites
bash tests/run_all.sh # same, without make
```

| Suite | What's tested |
|-------|--------------|
| `test_json.sh` | JSON syntax: settings.json + marketplace configs |
| `test_zsh.sh` | `zsh -n` syntax, brew plugin file paths, 7 required binaries |
| `test_tmux.sh` | Runtime syntax (isolated socket), duplicate bind-key detection |
| `test_nvim.sh` | `luac -p` on all Lua files, normal-mode keymap conflict detection, lldb-dap path |
| `test_tools.sh` | All Brewfile formulas + casks installed, 18 key binaries in PATH |
| `test_stow.sh` | Stow package dirs, 7 symlink targets, zshrc bootstrap, marketplace JSONs tracked |

The pre-commit hook reminds you to run tests when config files change.

---

## Secrets & Sensitive Config

`~/.config/secrets` is sourced by `.zshrc` and is **not in the repo**. Create manually on new machines:

```bash
# ~/.config/secrets
export ANTHROPIC_API_KEY="sk-ant-..."
export AWS_PROFILE="default"
export AWS_REGION="us-east-1"
# add other API keys, tokens, etc.
```

---

## .gitignore Conventions

- `*.json` ignored globally
- Exception: `!claude/**/*.json` — covers `settings.json` + all marketplace plugin JSONs
- `*.log` ignored
- Secret patterns: `.secrets`, `.env`, `.env.*`, `*.key`, `secrets/`

---

## Local Claude Marketplace

`claude/local-marketplace/` is symlinked to `~/.claude/local-marketplace/` and registered
in `claude/settings.json` as the `local-dotfiles` marketplace source.

Plugin: **dotfiles-tools**
- Invoke: `/dotfiles-tools:dotfiles-check`
- Checks: config syntax, keybinding conflicts, .gitignore coverage, stow layout, stray files, tool availability
FOOTER_STATIC

} > "$OUTPUT"

printf '\033[32m✓\033[0m CLAUDE.md regenerated → %s\n' "$OUTPUT"
printf '  %s lines\n' "$(wc -l < "$OUTPUT")"
